Feature/api resolve
McCue-Software-Solutions/jresolve pull request #14
Opened 2023-02-21 22:22 UTC by jpr4428

Merging work from Friday to main.

2023-02-21 22:41 UTC, bowbahdoe requested changes

2023-02-21 22:41 UTC, bowbahdoe commented on .metals/metals.lock.db
> +#FileLock
All these metals files shouldnt be here

2023-02-21 22:41 UTC, bowbahdoe commented on cache/https/repo.maven.apache.org/maven2/org/clojure/clojure/1.11.0/clojure-1.11.0.pom
> +<?xml version="1.0" encoding="UTF-8"?>
Add cache/ to gitignore

2023-02-23 19:54 UTC, npetrangelo approved these changes

2023-02-23 19:58 UTC, bowbahdoe approved these changes

2023-02-23 19:59 UTC, merged