Feature/pom parser variable replacement
McCue-Software-Solutions/jresolve pull request #16
Opened 2023-02-26 16:52 UTC by camperdue42

Alter the POM parser in order to replace variables within dependencies with the actual desired version.

2023-02-26 17:00 UTC, bowbahdoe requested changes

2023-02-26 17:00 UTC, bowbahdoe commented on src/main/java/dev/mccue/resolve/maven/ModelParseException.java
> +public class ModelParseException extends Throwable{
Extend `Exception` if you want a checked exception. `RuntimeException` if not

2023-02-26 17:00 UTC, bowbahdoe commented on src/main/java/dev/mccue/resolve/maven/PomParser.java
> +                final var matcher = Pattern.compile("\\$\\{(.*?)\\}").matcher(dependency.second().version());
Can these substitutions be combined with other stuff? like `${some.thing}.5`?

2023-02-26 17:00 UTC, bowbahdoe commented on src/main/java/dev/mccue/resolve/maven/PomParser.java
> +                                throw new ModelParseException("Undefined variable used in the POM");
Maybe include the name of the variable

2023-02-26 17:00 UTC, bowbahdoe commented on src/test/java/dev/mccue/resolve/maven/PomParserTest.java
>                          <dependency>
Instead of changing this test, add another test

2023-02-28 22:58 UTC, zsteig approved these changes

2023-03-07 22:50 UTC, bowbahdoe approved these changes

2023-03-09 20:00 UTC, merged